import{a as y,S as L,i as a}from"./assets/vendor-74e5960e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const v="44070531-25bb98da1641556d9bb7c94d1",S="https://pixabay.com/api/";async function f(e,t=1,s=15){return(await y.get(S,{params:{key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:s}})).data.hits}let m;function b(){const e=document.querySelector(".gallery");e.innerHTML=""}function g(e){const t=document.querySelector(".gallery"),s=e.map(n=>q(n)).join("");t.insertAdjacentHTML("beforeend",s),m?m.refresh():m=new L(".gallery a")}function q(e){return`
    <div class="image-card">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      </a>
      <div class="image-info">
        <p><strong>Likes:</strong> ${e.likes}</p>
        <p><strong>Views:</strong> ${e.views}</p>
        <p><strong>Comments:</strong> ${e.comments}</p>
        <p><strong>Downloads:</strong> ${e.downloads}</p>
      </div>
    </div>
  `}function p(){document.querySelector(".loader").classList.remove("hidden")}function l(){document.querySelector(".loader").classList.add("hidden")}const E=document.querySelector("#search-form"),w=document.querySelector('input[name="query"]'),d=document.querySelector(".load-more"),h=document.querySelector(".end-of-results");document.querySelector(".loader");let c=1,i="";E.addEventListener("submit",P);d.addEventListener("click",I);function P(e){if(e.preventDefault(),i=w.value.trim(),i===""){a.error({title:"Error",message:"Please enter a search term."});return}c=1,b(),O(),p(),f(i,c).then(t=>{l(),t.length>0?(g(t),d.classList.remove("hidden")):a.info({title:"Info",message:"No images found."})}).catch(t=>{l(),console.error("Error searching for images:",t),a.error({title:"Error",message:"Failed to load images. Please try again later."})})}function I(){c+=1,p(),f(i,c).then(e=>{l(),e.length>0?g(e):(d.classList.add("hidden"),h.classList.remove("hidden"))}).catch(e=>{l(),console.error("Error loading more images:",e),a.error({title:"Error",message:"Failed to load more images. Please try again later."})})}function O(){d.classList.add("hidden"),h.classList.add("hidden")}
//# sourceMappingURL=commonHelpers.js.map
