import{i as c,S as f}from"./assets/vendor-8501dee5.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const L="44070531-25bb98da1641556d9bb7c94d1";async function y(e){const o=`https://pixabay.com/api/?key=${L}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true`;try{const r=await fetch(o);if(!r.ok)throw new Error("Network response was not ok");return(await r.json()).hits}catch(r){throw console.error("Error fetching data:",r),r}}function w(){const e=document.querySelector(".gallery");e.innerHTML=""}function h(e){const o=document.querySelector(".gallery");if(e.length===0){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}e.forEach(r=>{const a=document.createElement("a");a.href=r.largeImageURL,a.classList.add("card"),a.innerHTML=`
      <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy">
      <div class="card-info">
        <p>Likes: ${r.likes}</p>
        <p>Views: ${r.views}</p>
        <p>Comments: ${r.comments}</p>
        <p>Downloads: ${r.downloads}</p>
      </div>
    `,o.appendChild(a)}),new f(".gallery a").refresh()}function p(){document.querySelector(".loader").style.display="block"}function l(){document.querySelector(".loader").style.display="none"}const S=document.querySelector("#search-form"),q=document.querySelector("#search-input"),b=document.querySelector(".gallery"),d=document.querySelector(".load-more");document.querySelector(".loader");const m=document.querySelector(".end-of-results");new f(".gallery a");let u=1,n="";S.addEventListener("submit",E);d.addEventListener("click",v);function E(e){if(e.preventDefault(),n=q.value.trim(),!n){c.error({title:"Error",message:"Please enter a search term."});return}w(),p(),u=1,y(n).then(o=>{l(),h(o),g(o.totalHits)}).catch(o=>{l(),console.error("Error searching for images:",o),c.error({title:"Error",message:"Failed to load images. Please try again later."})})}async function v(){u++,p();try{const e=await y(n,u);l(),h(e),g(e.totalHits)}catch(e){l(),console.error("Error loading more images:",e),c.error({title:"Error",message:"Failed to load more images. Please try again later."})}}function g(e){b.querySelectorAll(".image-card").length<e?(d.classList.remove("hidden"),m.classList.add("hidden")):(d.classList.add("hidden"),m.classList.remove("hidden"))}
//# sourceMappingURL=commonHelpers.js.map
